#!/usr/bin/env python3
"""Self-host the Google fonts used by the app.

    python3 scripts/self-host-fonts.py

The stylesheet used to do `@import url('https://fonts.googleapis.com/...')`.
Every page load then waited on a third party, and on a machine that cannot reach
fonts.googleapis.com the browser logged a failed request and painted a fallback
typeface instead. This app tells people their data stays here; its fonts should
too.

Downloads the woff2 files into frontend/public/fonts, writes
frontend/src/app/fonts.css with matching @font-face rules, and prints what it did.
Re-run it to refresh a family — the file names only change if Google's subsets do.
"""

import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, 'frontend', 'public', 'fonts')
CSS_OUT = os.path.join(ROOT, 'frontend', 'src', 'app', 'fonts.css')

FAMILIES = [
    ('Inter', 'Inter:wght@300;400;500;600;700;800;900'),
    ('Space Grotesk', 'Space+Grotesk:wght@400;500;600;700'),
    ('JetBrains Mono', 'JetBrains+Mono:wght@400;500;600'),
]
# Latin covers the product's own copy; latin-ext keeps accented names correct.
KEEP_SUBSETS = {'latin', 'latin-ext'}

UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
      'Chrome/140.0.0.0 Safari/537.36')


def fetch(url, binary=False):
    request = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = response.read()
    return data if binary else data.decode('utf-8')


def css_url(querystring):
    return f'https://fonts.googleapis.com/css2?family={querystring}&display=swap'


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    blocks_out = []
    downloaded = 0

    for family, query in FAMILIES:
        css = fetch(css_url(query))
        # Google puts a /* subset */ comment before each @font-face block.
        for comment, block in re.findall(r'/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S):
            if comment not in KEEP_SUBSETS:
                continue
            match = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block)
            if not match:
                continue
            source = match.group(1)
            weight = (re.search(r'font-weight:\s*(\d+)', block) or [None, '400'])[1]
            slug = f"{family.lower().replace(' ', '-')}-{weight}-{comment}.woff2"
            target = os.path.join(FONT_DIR, slug)
            if not os.path.exists(target):
                with open(target, 'wb') as handle:
                    handle.write(fetch(source, binary=True))
                downloaded += 1
            blocks_out.append(
                block.replace(match.group(0), f'url(/fonts/{slug})')
            )

    header = (
        '/* Self-hosted fonts. Generated by scripts/self-host-fonts.py —\n'
        '   do not edit by hand; re-run the script instead. */\n\n'
    )
    with open(CSS_OUT, 'w') as handle:
        handle.write(header + '\n'.join(blocks_out) + '\n')

    total = sum(os.path.getsize(os.path.join(FONT_DIR, f)) for f in os.listdir(FONT_DIR))
    print(f'downloaded {downloaded} new file(s); {len(os.listdir(FONT_DIR))} total in public/fonts')
    print(f'{len(blocks_out)} @font-face rules written to {os.path.relpath(CSS_OUT, ROOT)}')
    print(f'total weight: {total // 1024} KB')


if __name__ == '__main__':
    main()
